version: '3'
services:
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./backup:/app/backup
      - ./downloads:/app/downloads
    environment:
      - TZ=Europe/Paris
    ports:
      - "8901:8901"
    restart: unless-stopped
