server:
  - name: default
    protocol: http
    host: 192.168.9.3
    port: 80
    timezone: Europe/Paris
    message: Welcome to m3u-filter
  - name: extern
    protocol: https
    host: m3u-filter.mydns.com
    port: 443
    rtmp_port:
    timezone: Europe/Paris
    message: Welcome to m3u-filter
    path: m3uflt # optional, only needed for easier reverse proxy configuration see README.md.
user:
  - target: pl1
    credentials:
      - {username: x3452, password: ztrhgrGZrt83hjerter, token: 4243234wer234er234, proxy: redirect, server: default}
      - {username: x3453, password: kljlkjorn87jfkhksdh, token: 43dfgerrt345345ss4, proxy: reverse, server: extern, epg_timeshift: -02:30}